import { Product } from '@/common/types';
import manClothing from '../images/manClothing.png';
import womanClothing from '../images/womanClothing.png';

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Classic T-Shirt',
    price: 19.99,
    image: manClothing,
    category: 'T-Shirts',
    gender: 'men',
    description: 'A classic cotton t-shirt, perfect for everyday wear.',
  },
  {
    id: 6,
    name: 'Blazer',
    price: 79.99,
    image: womanClothing,
    category: 'Jackets',
    gender: 'women',
    description: 'A fashionable blazer, perfect for formal occasions.',
  },
  {
    id: 7,
    name: 'Hoodie',
    price: 39.99,
    image: manClothing,
    category: 'Sweaters',
    gender: 'men',
    description: 'A comfortable hoodie for casual wear.',
  },
  {
    id: 8,
    name: 'High Heels',
    price: 59.99,
    image: womanClothing,
    category: 'Shoes',
    gender: 'women',
    description: 'Elegant high heels, perfect for special events.',
  },
  {
    id: 9,
    name: 'Jeans',
    price: 44.99,
    image: manClothing,
    category: 'Pants',
    gender: 'men',
    description: 'Classic denim jeans, durable and stylish.',
  },
  {
    id: 10,
    name: 'Leggings',
    price: 29.99,
    image: womanClothing,
    category: 'Pants',
    gender: 'women',
    description: 'Stretchy and comfortable leggings for workouts or casual wear.',
  },
  {
    id: 11,
    name: 'Sneakers',
    price: 74.99,
    image: manClothing,
    category: 'Shoes',
    gender: 'men',
    description: 'Stylish sneakers for everyday use.',
  },
  {
    id: 12,
    name: 'Summer Dress',
    price: 49.99,
    image: womanClothing,
    category: 'Dresses',
    gender: 'women',
    description: 'Light and comfortable summer dress.',
  },
  {
    id: 13,
    name: 'Formal Shirt',
    price: 34.99,
    image: manClothing,
    category: 'Shirts',
    gender: 'men',
    description: 'A perfect shirt for formal occasions.',
  },
  {
    id: 14,
    name: 'Crop Top',
    price: 24.99,
    image: womanClothing,
    category: 'Tops',
    gender: 'women',
    description: 'Trendy crop top for casual outings.',
  },
  {
    id: 15,
    name: 'Sweater',
    price: 54.99,
    image: manClothing,
    category: 'Sweaters',
    gender: 'men',
    description: 'Warm and comfortable sweater.',
  },
  {
    id: 16,
    name: 'Cardigan',
    price: 64.99,
    image: womanClothing,
    category: 'Sweaters',
    gender: 'women',
    description: 'Cozy cardigan for chilly days.',
  },
];
